### PR TITLE
Add Prettier options from newer versions

### PR DESCRIPTION
**Pull request by mmiller42**
https://prettier.io/docs/en/configuration.html

### CODE REVIEW

**Review by goto-bus-stop — COMMENTED** [review]
Thanks for the PR! I omitted some of the options because they don't make sense for a Babel generator, which always outputs full JS files.

- `rangeStart` / `rangeEnd` - unused because prettier has to output the entire file
- `parser` - unused because Babel does the parsing, not prettier
- `filepath` - unused because Babel provides the file names
- `proseWrap` - is for markdown files, not JS
- `htmlWhitespaceSensitivity` - is for HTML files, not JS
- `vueIndentScriptAndStyle` - is for vue files, not JS

Could you remove those?

**Comment by mmiller42** [comment]
Yep, makes sense, updated.

**Review by goto-bus-stop — APPROVED** [review]
Thanks!!

**Comment by goto-bus-stop** [comment]
:package: 1.2.0

**Pull request merged**
